### ISSUE TITLE
Good work wrapping sections in container divs

### ISSUE THREAD

**Issue by griffinlacek** [emptypool/prj-rev-bwfs-dasmoto#1]
You've got all your code sections inside container divs, which is great for readability and makes layout/styling easier! This is a good practice so keep it up! 

https://github.com/emptypool/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L9-L29

**Comment by emptypool** [comment]
Thank again for all your time and thoughtful consideration !! Have a great week.
