### ISSUE TITLE
Setting font-family

### ISSUE THREAD

**Issue by griffinlacek** [emptypool/prj-rev-bwfs-dasmoto#2]
You've got font-family successfully set on all needed elements, but you've had to list each element out in your CSS. You could achieve the same by just targeting body and setting font-family on that. Always consider ways to reduce code and make it more simple! Just something to keep in mind!

https://github.com/emptypool/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/style.css#L1-L3

**Comment by emptypool** [comment]
that makes so much sense to me now after having completed the "excursions" assignment. Body text was set first so the type was consistent throughout, without adding "font-family" to each element. If a bold or color change was required, then that element could be changed accordingly. thanks again - makes everything simpler, or "streamlined" for lack of a better term.
